Add a test coverage tool
* cowboy was added as a fix, to get hackney to compile under test.
  Without cowboy, the error is:
```
==> hackney (compile)
WARN:  Expected /home/joe/elixir/exdm/deps/cowboy to be an app dir
(containing ebin/*.app), but no .app found.
Dependency not available: cowboy-.* ({git,
                                      "https://github.com/ninenines/cowboy.git",
                                      {tag,"1.0.4"}})
ERROR: compile failed while processing
/home/joe/elixir/exdm/deps/hackney: rebar_abort
** (Mix) Could not compile dependency hackney, /home/joe/.mix/rebar
command failed. If you want to recompile this dependency, please run:
mix deps.compile hackney
```